apiVersion: backstage.io/v1alpha1
kind: environment-provider
metadata:
  name: ${{values.name | dump}}
  {%- if values.description %}
  description: ${{values.description | dump}}
  {%- endif %}
  annotations:
    backstage.io/orphan: 'true'
spec:
  type: environment-provider
  lifecycle: experimental
  owner: ${{values.owner | dump}}
