apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: crossplane-poc-cluster
  region: eu-west-2

nodeGroups:
  - name: ng-1
    instanceType: m5.large
    desiredCapacity: 2
    volumeSize: 80
