apiVersion: v1
kind: Service
metadata:
  name: backstage
  namespace: backstage
spec:
  type: LoadBalancer
  selector:
    app: backstage
  ports:
    - name: http
      port: 8081
      targetPort: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage
  namespace: backstage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backstage
  template:
    metadata:
      labels:
        app: backstage
    spec:
      containers:
        - name: backstage
          image: 043264546031.dkr.ecr.eu-west-3.amazonaws.com/backstage-devex-poc:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          envFrom:
            - secretRef:
                name: backstage-secrets
