apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: initteams.customplatform.crossplane.io
spec:
  connectionSecretKeys:
    - kubeconfig
  group: customplatform.jaruiz.io/v1
  names:
    kind: InitTeam
    plural: initteams
  claimNames:
    kind: InitTeamClaim
    plural: initteamsclaims
  versions:
    - name: v1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                team:
                  type: object
                  properties:
                    name:
                      type: string
                      description: Team name.
                  required:
                    - name
              required:
                - team
