apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: repositories
  labels:
    group: onboarding
spec:
  patchSets:
    - name: metadata
      patches:
        - fromFieldPath: metadata.labels
  compositeTypeRef:
    apiVersion: jaruiz.crossplane.io/v1
    kind: repository
  resources:
#    - name: gitlab-provider-config
#      base:
#        apiVersion: gitlab.crossplane.io/v1beta1
#        kind: ProviderConfig
#        metadata:
#          name: gitlab-provider
#        spec:
#          baseURL: https://git.paradigmadigital.com/
#          credentials:
#            secretRef:
#              key: token
#              name: gitlab-credentials
#              namespace: crossplane-system
#            source: Secret
#      patches:
#        - fromFieldPath: spec.name
#          toFieldPath: metadata.name
#          transforms:
#            - type: string
#              string:
#                fmt: "%s-gitlab-provider-config"
#        - fromFieldPath: spec.name
#          toFieldPath: spec.credentials.secretRef.name
#          transforms:
#            - type: string
#              string:
#                fmt: "%s-conn"
#      readinessChecks:
#        - type: None
    - name: gitlab-group
      base:
        apiVersion: groups.gitlab.crossplane.io/v1alpha1
        kind: Group
        spec:
          forProvider:
            description: example group description
            name: Example Group
            path: example-group-path
          providerConfigRef:
            name: gitlab-provider
      patches:
        - fromFieldPath: spec.name
          toFieldPath: metadata.name
          transforms:
            - type: string
              string:
                fmt: "%s-gitlab-group"
        - fromFieldPath: spec.name
          toFieldPath: spec.forProvider.description
          transforms:
            - type: string
              string:
                fmt: "%s group to manage repositories"
        - fromFieldPath: spec.name
          toFieldPath: spec.forProvider.name
          transforms:
            - type: string
              string:
                fmt: "%s group"
        - fromFieldPath: spec.name
          toFieldPath: spec.forProvider.path
          transforms:
            - type: string
              string:
                fmt: "%s-group"
#        - fromFieldPath: spec.name
#          toFieldPath: spec.providerConfigRef.name
#          transforms:
#            - type: string
#              string:
#                fmt: "%s-gitlab-provider-config"
    - name: gitlab-project
      base:
        apiVersion: projects.gitlab.crossplane.io/v1alpha1
        kind: Project
        spec:
          forProvider:
            description: example project description
            name: project-crossplane
          providerConfigRef:
            name: gitlab-provider
      patches:
        - fromFieldPath: spec.name
          toFieldPath: metadata.name
          transforms:
            - type: string
              string:
                fmt: "%s-project"
