apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: platformsbase.jaruiz.crossplane.io
spec:
  connectionSecretKeys:
    - kubeconfig
  group: jaruiz.crossplane.io
  names:
    kind: platformbase
    plural: platformsbase
  claimNames:
    kind: platformbaseclaim
    plural: platformbaseclaims
  versions:
    - name: v1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                  description: Name of this Cluster that other objects will use to refer to it.
              required:
                - name
#            status:
#              type: object
#              properties:
#                clusterName:
#                  description: The name of the cluster
#                  type: string
#                controlPlaneStatus:
#                  description: The status of the control plane
#                  type: string
#                nodePoolStatus:
#                  description: The status of the node pool
#                  type: string
#      additionalPrinterColumns:
#        - name: clusterName
#          type: string
#          jsonPath: ".status.clusterName"
#        - name: controlPlane
#          type: string
#          jsonPath: ".status.controlPlaneStatus"
#        - name: nodePool
#          type: string
#          jsonPath: ".status.nodePoolStatus"
