apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: platformsinfra.jaruiz.crossplane.io
spec:
  connectionSecretKeys:
    - kubeconfig
  group: jaruiz.crossplane.io
  names:
    kind: PlatformInfra
    plural: platformsinfra
  claimNames:
    kind: PlatformInfraClaim
    plural: platforminfraclaims
  versions:
    - name: v1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                  description: Name of the team requested the platform.
              required:
                - name

