apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: platformscicd.jaruiz.crossplane.io
spec:
  connectionSecretKeys:
    - kubeconfig
  group: jaruiz.crossplane.io
  names:
    kind: PlatformCICD
    plural: platformscicd
  claimNames:
    kind: PlatformCICDClaim
    plural: platformcicdclaims
  versions:
    - name: v1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                  description: Name of this Cluster that other objects will use to refer to it.
              required:
                - name
