apiVersion: gitlab.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: gitlab-provider
spec:
  baseURL: https://gitlab.com/
  credentials:
    secretRef:
      key: token
      name: gitlab-credentials
      namespace: crossplane-system
    source: Secret
