kind: Service
apiVersion: v1
metadata:
  name: kafdrop
  namespace: kafka
  labels:
    app: kafdrop
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: 8081
  selector:
    deployment: kafdrop
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: kafdrop
  namespace: kafka
  labels:
    app: kafdrop
data:
  KAFKA_BROKERCONNECT: 'my-cluster-kafka-bootstrap:9092'
  SERVER_SERVLET_CONTEXTPATH: '/'
  SERVER_PORT: '8081'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafdrop
  namespace: kafka
  labels:
    app: kafdrop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafdrop
  template:
    metadata:
      labels:
        app: kafdrop
        deployment: kafdrop
        maistra.io/expose-route: 'true'
    spec:
      nodeSelector:
        critical: "true"
      containers:
        - name: kafdrop
          image: obsidiandynamics/kafdrop
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: kafdrop
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
