image: node:18
variables:
  AWS_ACCOUNT: "${{ values.aws_account }}"
  AWS_DEFAULT_REGION: "${{ values.aws_region }}"
  AWS_BUCKET_NAME: "${{ values.aws_bucket_name }}"

stages:
  - build
build-and-package:
  stage: build
  before_script:
    - cat /etc/os-release
    - apt-get update
    - python3 -V
    - apt install -yq python3-pip
    - export PIP_BREAK_SYSTEM_PACKAGES=1
    - pip3 install awscli --upgrade
    - pip3 install aws-sam-cli --upgrade
    - aws sts get-caller-identity
    - apt install nodejs npm -y
    - node -v
  script:
    - sam build
    - sam package --force-upload --s3-bucket $AWS_BUCKET_NAME --output-template-file packaged.yaml
    # put the latest build file into S3 and overwrite the previous file
    - aws s3api put-object --bucket $AWS_BUCKET_NAME --key packaged.yaml --body packaged.yaml
    # put the build file into S3 with a timestamp so that it wont get overwritten by other builds
    - export today=$(date +%m-%d-%Y_%H-%M-%S)
    - aws s3api put-object --bucket $AWS_BUCKET_NAME --key packaged-${today}.yaml --body packaged.yaml
    - cat packaged.yaml
    - echo "SUCCESS"
